### PR TITLE
Update of the material for the website

### PR DESCRIPTION
**Pull request by matthieu-bruneaux**
Just added a section in the course outline about the teachers for each topic and the time table. All of this is tentative for now, but once we (Carlos and Matthieu) agree on the topic assignment we can start working on the preparation of the material itself!

### CODE REVIEW

**Comment by carlosp420** [comment]
the live website here http://mdjbru-teaching-material.github.io/turku_course/ is pulling the source code to generate the pages from your repository right?
then maybe I should be the one doing pull requests to your repo? :smile_cat:

**Comment by carlosp420** [comment]
:speak_no_evil:

**Comment by matthieu-bruneaux** [comment]
I guess you are right Carlos, maybe it will be easier for the website update :) Do you know how this would work? Is it just a matter of you pulling and pushing to me, or do we have to swap the origin/fork status of the repositories?

**Comment by carlosp420** [comment]
I will update my add your repo url to my upstream. Hopefully that would be enough? :dragon_face:

**Comment by matthieu-bruneaux** [comment]
Ok! Since my repo has your repo as upstream, maybe it will make an infinite loop :star2:  So I should probably remove your repo from my upstream also. I am doing it now!

**Comment by matthieu-bruneaux** [comment]
I removed your repo from "upstream" on my local repo and tried to push to github, but nothing happened... There is this thread on stackoverflow http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository where they suggest that one has to contact the support from github, or to delete the github repo and recreate it from the local repositories

**Comment by matthieu-bruneaux** [comment]
So one way to go could be:
- I remove my github repository that was forked from yours
- you remove your original github repo
- I create a new repository with the same name (but this one is not a fork from yours now)
- I push my local copy of the repo there
- you fork this repo to your account

What do you think?

**Comment by carlosp420** [comment]
sounds good, lets do this

**Pull request merged**
